tictactoe game
chuck032/Sparta-global-tictactoe pull request #1
Opened 2018-04-27 00:16 UTC by chuck032

completed majority of the game, although i was unable to make the winner visible and check if either X or O had won

2018-04-27 10:49 UTC, JSChilds commented on script.js
> +//
Don't leave commented-out code in your final product.

2018-04-27 10:49 UTC, JSChilds commented on script.js
> +
All this should be indented within the function.

2018-04-27 10:50 UTC, JSChilds commented on script.js
> +
Don't have big, inconsistent spaces like this.

2018-04-27 10:50 UTC, JSChilds commented on script.js
> +    checkWin()
Remember your semicolons.

2018-04-27 10:53 UTC, JSChilds commented on script.js
> +
You aren't actually getting the elements you want back, here.

2018-04-27 10:55 UTC, JSChilds requested changes
Good effort, Chuck and the logic and win conditions all look sound - you just aren't getting the right elements you need to check back from your queries. In the future, make sure when you grab an element from the DOM, you test straight away that you've got back what you expected before you start trying to do stuff to it.

2018-04-28 16:41 UTC, chuck032 commented
Was able to make the win conditions work and i've also cleaned it up so there is commented out code and indentation looks better

2018-06-04 21:04 UTC, merged